name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: # Ensure required permissions for dependency graph submission
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -DSENTRY_ORG ${{ secrets.SENTRY_ORG }} \
          -DSENTRY_PROJECT ${{ secrets.SENTRY_PROJECT }} \
          -DSENTRY_AUTH_TOKEN ${{ secrets.SENTRY_AUTH_TOKEN }} \
          -B package --file pom.xml

    # Uploads the dependency graph snapshot to GitHub
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
